# use a light weight python image and install required packages in requirements.txt

FROM python:3.9-slim

# install git
RUN apt-get update && apt-get install -y git

# install sudo apt-get install build-essential python-dev
RUN apt-get update && apt-get install -y build-essential

#upgrade pip
RUN pip install --upgrade pip

# Set the working directory in the container
WORKDIR /get_data_from_db

# Copy the current directory contents into the container at /app, except for the dockerfile
COPY . /get_data_from_db

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run jupyter notebook when the container launches
RUN rm -rf /get_data_from_db/dockerfile /get_data_from_db/requirements.txt

# CMD run main.sh
RUN chmod +x main.sh
CMD ["./main.sh"]



