# use a light weight python image and install required packages in requirements.txt

FROM python:3.9-slim

# install git
RUN apt-get update && apt-get install -y git

# install sudo apt-get install build-essential python-dev
RUN apt-get update && apt-get install -y build-essential

#upgrade pip
RUN pip install --upgrade pip

# Set the working directory in the container
WORKDIR /deeph

# Copy the current directory contents into the container at /app, except for the dockerfile
COPY . /deeph

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run jupyter notebook when the container launches
RUN rm -rf /deeph/dockerfile /deeph/requirements.txt

# install jupyter
RUN pip install jupyter

# Expose the port the app runs on
EXPOSE 8888

# Start the jupyter notebook and run main.ipynb
CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]




